"""
enrich_earnings_dates.jl

For each confidence-scored NSE company, fetch historical earnings release dates
from Tijori and project the next expected earnings date forward.

Results are written to website/data/earnings_projections.json — a lightweight
symbol → next_earnings map consumed by generate_earnings_watchlist.jl.

Run this every 1–2 weeks. The script is resumable: companies already present
in the output file are skipped unless --refresh is passed.

Prerequisites:
  - Tijori sidecar running on port 3001 (node sidecar/server_http.js)
  - website/data/nse_companies_latest.json generated by generate_nse_list.jl

Usage:
  julia --project=packages/TijoriData scripts/enrich_earnings_dates.jl
  julia --project=packages/TijoriData scripts/enrich_earnings_dates.jl 50      # top N by mktcap
  julia --project=packages/TijoriData scripts/enrich_earnings_dates.jl --refresh # re-fetch all
"""

using TijoriData, JSON3, Dates, Printf

const SIDECAR_PORT = 3001
const COMPANIES_FILE   = joinpath(@__DIR__, "..", "website", "data", "nse_companies_latest.json")
const PROJECTIONS_FILE = joinpath(@__DIR__, "..", "website", "data", "earnings_projections.json")

const MONTH_ABBR = Dict(
    "Jan"=>1,"Feb"=>2,"Mar"=>3,"Apr"=>4,"May"=>5,"Jun"=>6,
    "Jul"=>7,"Aug"=>8,"Sep"=>9,"Oct"=>10,"Nov"=>11,"Dec"=>12,
)

# ── Helpers ───────────────────────────────────────────────────────────────────

function parse_period(s::AbstractString)::Union{Date, Nothing}
    parts = split(strip(s))
    length(parts) == 2 || return nothing
    month = get(MONTH_ABBR, parts[1], nothing)
    isnothing(month) && return nothing
    year  = tryparse(Int, parts[2])
    isnothing(year)  && return nothing
    return Date(year, month, 1)
end

function project_next(releases::Vector)::Union{Dict{String,Any}, Nothing}
    isempty(releases) && return nothing

    dates = sort(filter(!isnothing, [parse_period(string(r.period)) for r in releases]))
    length(dates) < 2 && return nothing

    # Gaps between consecutive releases in days
    gaps = [Dates.value(dates[i] - dates[i-1]) for i in 2:length(dates)]
    # Keep only plausible quarterly / half-yearly gaps
    valid = filter(g -> 60 <= g <= 210, gaps)
    isempty(valid) && return nothing

    sorted_gaps  = sort(valid)
    median_gap   = sorted_gaps[div(length(sorted_gaps) + 1, 2)]
    gap_std      = length(valid) > 1 ? sqrt(sum((g - median_gap)^2 for g in valid) / length(valid)) : 999.0

    # Project forward from the most recent release until we're past today
    next_date = dates[end] + Day(median_gap)
    while next_date < today()
        next_date += Day(median_gap)
    end

    conf_level = length(dates) >= 4 && gap_std < 15 ? "high"   :
                 length(dates) >= 2                  ? "medium" : "low"

    return Dict{String,Any}(
        "projected_date"   => string(next_date),
        "projected_month"  => Dates.format(next_date, "yyyy-mm"),
        "median_gap_days"  => median_gap,
        "gap_std_days"     => round(gap_std, digits=1),
        "last_release"     => string(dates[end]),
        "releases_used"    => length(dates),
        "projection_confidence" => conf_level,
        "source"           => "tijori_history",
        "enriched_at"      => string(now(UTC)),
    )
end

# ── Main ──────────────────────────────────────────────────────────────────────

function main()
    if "--help" in ARGS || "-h" in ARGS
        println("""
Usage:
  julia --project=packages/TijoriData scripts/enrich_earnings_dates.jl [N] [--refresh]

Arguments:
  N          Optional. Number of top companies by market cap to process (default: all scored).
  --refresh  Re-fetch all companies, ignoring any existing projections file.

Options:
  -h, --help   Show this message and exit.

Prerequisites:
  - Tijori sidecar running on port 3001 (node sidecar/server_http.js)
  - website/data/nse_companies_latest.json present

Output:
  website/data/earnings_projections.json
""")
        return
    end

    refresh = "--refresh" in ARGS
    args    = filter(a -> a != "--refresh", ARGS)
    top_n   = length(args) >= 1 ? parse(Int, args[1]) : typemax(Int)

    # ── Connect ───────────────────────────────────────────────────────────────

    TijoriData.configure!(port=SIDECAR_PORT)
    TijoriData.is_running() || error("Sidecar not reachable on port $SIDECAR_PORT. " *
                                      "Run: node sidecar/server_http.js")
    @info "Sidecar OK on port $SIDECAR_PORT"

    # ── Load companies ────────────────────────────────────────────────────────

    isfile(COMPANIES_FILE) || error("Not found: $COMPANIES_FILE\nRun: julia scripts/generate_nse_list.jl")

    raw     = JSON3.read(read(COMPANIES_FILE, String))
    all_c   = collect(raw.companies)

    # Only process companies that have been confidence-scored and have a slug
    eligible = filter(all_c) do c
        !isnothing(get(c, :confidence, nothing)) &&
        !isempty(string(get(c, :slug, "")))
    end
    sort!(eligible, by = c -> Float64(get(c, :market_cap_cr, 0.0)), rev=true)
    todo = first(eligible, top_n)

    @info "$(length(eligible)) scored companies found, processing $(length(todo))"

    # ── Load existing projections (for resume) ────────────────────────────────

    existing = Dict{String,Any}()
    if !refresh && isfile(PROJECTIONS_FILE)
        try
            proj = JSON3.read(read(PROJECTIONS_FILE, String))
            for (sym, val) in pairs(proj.projections)
                existing[string(sym)] = val
            end
            @info "Loaded $(length(existing)) existing projections (skipping these unless --refresh)"
        catch
            @warn "Could not read existing projections file — starting fresh"
        end
    end

    # ── Process ───────────────────────────────────────────────────────────────

    projections = copy(existing)
    skipped = failed = projected = 0
    total = length(todo)

    for (i, c) in enumerate(todo)
        sym  = string(get(c, :symbol, ""))
        slug = string(get(c, :slug, ""))
        name = string(get(c, :name, ""))

        # Skip if already projected and not refreshing
        if haskey(existing, sym) && !refresh
            skipped += 1
            continue
        end

        t0 = time()
        try
            kb       = get_knowledge_base(slug)
            releases = kb.earnings_releases
            proj     = project_next(releases)

            if isnothing(proj)
                projections[sym] = Dict{String,Any}(
                    "projected_date"        => nothing,
                    "projection_confidence" => "none",
                    "releases_used"         => length(collect(releases)),
                    "source"                => "tijori_history",
                    "enriched_at"           => string(now(UTC)),
                )
                @info @sprintf("[%d/%d] %-30s  no projection (only %d releases)",
                               i, total, name[1:min(30,length(name))], length(collect(releases)))
            else
                projections[sym] = proj
                projected += 1
                @info @sprintf("[%d/%d] %-30s  → %s  (%s, gap=%dd, %.1fs)",
                               i, total, name[1:min(30,length(name))],
                               proj["projected_month"], proj["projection_confidence"],
                               proj["median_gap_days"], time()-t0)
            end
        catch e
            failed += 1
            projections[sym] = Dict{String,Any}(
                "projected_date"        => nothing,
                "projection_confidence" => "error",
                "error"                 => sprint(showerror, e)[1:min(120,end)],
                "source"                => "tijori_history",
                "enriched_at"           => string(now(UTC)),
            )
            @warn @sprintf("[%d/%d] %-30s  ERROR: %s",
                           i, total, name[1:min(30,length(name))], sprint(showerror, e)[1:80])
        end

        # Save incrementally every 10 companies
        if i % 10 == 0 || i == total
            _save(projections)
        end
    end

    _save(projections)

    println()
    println("Enrichment complete:")
    @printf("  Projected:  %d\n", projected)
    @printf("  Skipped:    %d  (already in file)\n", skipped)
    @printf("  Failed:     %d\n", failed)
    @printf("  Total:      %d\n", length(projections))
    println()
    println("Output: $PROJECTIONS_FILE")
end

function _save(projections::Dict)
    payload = Dict{String,Any}(
        "generated_at" => string(now(UTC)),
        "total"        => length(projections),
        "projections"  => projections,
    )
    mkpath(dirname(PROJECTIONS_FILE))
    open(PROJECTIONS_FILE, "w") do io
        JSON3.pretty(io, payload)
    end
end

main()
