"""
generate_earnings_watchlist.jl

Fetch upcoming NSE earnings events and join them with company confidence data,
producing data/earnings_watchlist_latest.json for the Watchlist page.

All companies that have been confidence-scored (by run_confidence_checks.jl)
are included regardless of score.

Prerequisites:
  - data/nse_companies_latest.json generated by generate_nse_list.jl
  - Confidence checks already run for relevant companies

Usage:
  julia --project=packages/EarningsCalendar scripts/generate_earnings_watchlist.jl
  julia --project=packages/EarningsCalendar scripts/generate_earnings_watchlist.jl 60
"""

using EarningsCalendar, JSON3, Dates, Printf

const DATA_FILE = joinpath(@__DIR__, "..", "website", "data", "nse_companies_latest.json")
const OUT_DIR   = joinpath(@__DIR__, "..", "website", "data")
const OUT_FILE  = joinpath(OUT_DIR, "earnings_watchlist_latest.json")

function main()
    if "--help" in ARGS || "-h" in ARGS
        println("""
Usage:
  julia --project=packages/EarningsCalendar scripts/generate_earnings_watchlist.jl [DAYS]

Arguments:
  DAYS   Optional. Number of calendar days to look ahead (default: 30).

Options:
  -h, --help   Show this message and exit.

Prerequisites:
  - website/data/nse_companies_latest.json present (julia scripts/generate_nse_list.jl)
  - Confidence checks run for companies of interest (julia --project=packages/CompanyConfidence scripts/run_confidence_checks.jl)

Output:
  website/data/earnings_watchlist_latest.json
""")
        return
    end

    window_days = length(ARGS) >= 1 ? parse(Int, ARGS[1]) : 30
    from_date   = today()
    to_date     = from_date + Day(window_days - 1)

    # ── Load company data ─────────────────────────────────────────────────────

    isfile(DATA_FILE) || error("Data file not found: $DATA_FILE\n" *
                                "Run: julia scripts/generate_nse_list.jl")

    raw   = JSON3.read(read(DATA_FILE, String))
    all_c = collect(raw.companies)

    # Build symbol → company dict (keep only confidence-scored companies)
    company_by_symbol = Dict{String, Any}()
    for c in all_c
        conf = get(c, :confidence, nothing)
        isnothing(conf) && continue
        sym = string(get(c, :symbol, ""))
        isempty(sym)   && continue
        company_by_symbol[sym] = c
    end

    n_eligible = length(company_by_symbol)
    @info "Loaded $(length(all_c)) companies, $n_eligible with confidence data"

    # ── Fetch upcoming earnings ───────────────────────────────────────────────

    @info "Fetching NSE earnings events for $from_date → $to_date ($window_days days)…"
    events = try
        fetch_earnings_calendar(from_date, to_date)
    catch e
        @error "Failed to fetch NSE calendar: $(sprint(showerror, e))"
        EarningsEvent[]
    end

    @info "  $(length(events)) earnings events found"

    # ── Join and filter ───────────────────────────────────────────────────────

    matched = Any[]
    seen    = Set{String}()   # deduplicate by symbol (take first/earliest)

    for ev in events
        haskey(company_by_symbol, ev.symbol) || continue
        ev.symbol in seen && continue
        push!(seen, ev.symbol)

        c = company_by_symbol[ev.symbol]
        conf = get(c, :confidence, nothing)

        push!(matched, Dict{String, Any}(
            "symbol"        => ev.symbol,
            "company"       => ev.company,
            "earnings_date" => string(ev.date),
            "days_until"    => (ev.date - today()).value,
            "purpose"       => ev.purpose,
            "sector"        => string(get(c, :sector,        nothing) === nothing ? "" : get(c, :sector, "")),
            "market_cap_cr" => get(c, :market_cap_cr, nothing),
            "close_price"   => get(c, :close_price,   nothing),
            "confidence"    => conf,
        ))
    end

    sort!(matched, by = e -> e["earnings_date"])

    @info "  $(length(matched)) companies matched (scored + upcoming earnings)"

    # ── Write output ──────────────────────────────────────────────────────────

    mkpath(OUT_DIR)
    payload = Dict{String, Any}(
        "generated_at" => string(now(UTC)),
        "from_date"    => string(from_date),
        "to_date"      => string(to_date),
        "window_days"  => window_days,
        "total"        => length(matched),
        "events"       => matched,
    )

    open(OUT_FILE, "w") do io
        JSON3.pretty(io, payload)
    end

    @info "Written: $OUT_FILE"

    # ── Summary ───────────────────────────────────────────────────────────────

    if !isempty(matched)
        println()
        println("Upcoming earnings (all scored companies, next $window_days days):")
        println("  Days  Score  Symbol          Company")
        println("  " * "─"^60)
        for e in matched
            days  = e["days_until"]
            score = e["confidence"] !== nothing ? string(round(Int, e["confidence"]["score"])) : "?"
            @printf("  %-5s %-6s %-15s %s\n", "in $days", score, e["symbol"], e["company"])
        end
    else
        println("\nNo scored companies have upcoming earnings in the next $window_days days.")
        println("Tip: run run_confidence_checks.jl first to score more companies.")
    end
end

main()
