"""
run_confidence_checks.jl

Run CompanyConfidence checks on the top N NSE companies by market cap
and merge the results back into the JSON data file.

Prerequisites:
  - Tijori sidecar running on port 3001
  - data/nse_companies_latest.json generated by generate_nse_list.jl

Usage:
  julia --project=packages/CompanyConfidence scripts/run_confidence_checks.jl
  julia --project=packages/CompanyConfidence scripts/run_confidence_checks.jl 500
"""

using CompanyConfidence, TijoriData, JSON3, Dates, Printf

const SIDECAR_PORT = 3001
const DATA_FILE    = joinpath(@__DIR__, "..", "data", "nse_companies_latest.json")

# ── Run checks ────────────────────────────────────────────────────────────────

function report_to_dict(r::ConfidenceReport)::Dict{String,Any}
    Dict{String,Any}(
        "score"       => r.score,
        "pass"        => r.pass,
        "checked_at"  => string(r.generated_at),
        "beneish"     => Dict{String,Any}(
            "applicable"    => r.beneish.applicable,
            "m_score"       => r.beneish.m_score,
            "is_flagged"    => r.beneish.is_flagged,
            "year_t"        => r.beneish.year_t,
            "year_t1"       => r.beneish.year_t1,
            "dsri"          => r.beneish.dsri,
            "gmi"           => r.beneish.gmi,
            "aqi"           => r.beneish.aqi,
            "sgi"           => r.beneish.sgi,
            "depi"          => r.beneish.depi,
            "sgai"          => r.beneish.sgai,
            "lvgi"          => r.beneish.lvgi,
            "tata"          => r.beneish.tata,
            "missing_items" => r.beneish.missing_items,
        ),
        "cashflow"    => Dict{String,Any}(
            "years_checked"   => r.cashflow.years_checked,
            "years_cfo_lt_ni" => r.cashflow.years_cfo_lt_ni,
            "avg_accrual_ratio" => r.cashflow.avg_accrual_ratio,
            "is_flagged"      => r.cashflow.is_flagged,
        ),
        "pledging"    => Dict{String,Any}(
            "latest_pct"    => r.pledging.latest_pct,
            "trend"         => string(r.pledging.trend),
            "change_4q"     => r.pledging.change_4q,
            "quarters_used" => r.pledging.quarters_used,
            "is_flagged"    => r.pledging.is_flagged,
        ),
        "forensics"   => Dict{String,Any}(
            "flag_count" => length(r.forensics.flags),
            "flags"      => r.forensics.flags,
            "is_flagged" => r.forensics.is_flagged,
        ),
        "surveillance" => Dict{String,Any}(
            "on_asm"    => r.surveillance.on_asm,
            "on_gsm"    => r.surveillance.on_gsm,
            "checked"   => r.surveillance.checked,
            "is_flagged" => r.surveillance.is_flagged,
        ),
    )
end

function main()
    if "--help" in ARGS || "-h" in ARGS
        println("""
Usage:
  julia --project=packages/CompanyConfidence scripts/run_confidence_checks.jl [N]

Arguments:
  N   Optional. Number of top companies by market cap to check (default: 100).

Options:
  -h, --help   Show this message and exit.

Prerequisites:
  - Tijori sidecar running on port 3001 (node sidecar/server_http.js)
  - data/nse_companies_latest.json present (julia scripts/generate_nse_list.jl)

Output:
  Merges a \"confidence\" key into each checked company in nse_companies_latest.json.
  Prints a league table of the top 20 by confidence score on completion.
""")
        return
    end

    top_n = length(ARGS) >= 1 ? parse(Int, ARGS[1]) : 100

    # ── Connect to running sidecar ────────────────────────────────────────────

    TijoriData.configure!(port=SIDECAR_PORT)
    TijoriData.is_running() || error("Sidecar not reachable on port $SIDECAR_PORT. " *
                                      "Run: node sidecar/server_http.js")
    @info "Sidecar OK on port $SIDECAR_PORT"

    # ── Load and sort company list ────────────────────────────────────────────

    isfile(DATA_FILE) || error("Data file not found: $DATA_FILE\n" *
                                "Run: julia scripts/generate_nse_list.jl")

    raw   = JSON3.read(read(DATA_FILE, String))
    all_c = collect(raw.companies)

    with_slug = filter(c -> !isnothing(get(c, :slug, nothing)) && !isempty(string(get(c, :slug, ""))), all_c)
    sort!(with_slug, by = c -> Float64(get(c, :market_cap_cr, 0.0)), rev=true)
    top = first(with_slug, top_n)

    @info "Running confidence checks on top $top_n companies by market cap"
    @info "Estimated time: $(top_n * 6) – $(top_n * 15) seconds"

    confidence_by_symbol = Dict{String,Any}()
    failed = String[]

    for (i, c) in enumerate(top)
        slug   = string(c.slug)
        symbol = string(c.symbol)
        name   = string(c.name)
        t0     = time()
        try
            report = analyze(slug; check_surveillance=false)
            confidence_by_symbol[symbol] = report_to_dict(report)
            elapsed = round(time() - t0, digits=1)
            score   = report.score
            verdict = report.pass ? "PASS" : "FAIL"
            @info "[$i/$top_n] $name  →  $score / 100  $verdict  ($(elapsed)s)"
        catch e
            push!(failed, "$symbol ($slug): $(sprint(showerror, e))")
            confidence_by_symbol[symbol] = nothing
            @warn "[$i/$top_n] $name  →  ERROR: $(sprint(showerror, e))"
        end
    end

    # ── Merge back into full company list ─────────────────────────────────────

    updated_companies = map(all_c) do c
        sym  = string(get(c, :symbol, ""))
        conf = get(confidence_by_symbol, sym, missing)
        d = Dict{String,Any}(string(k) => v for (k, v) in pairs(c))
        ismissing(conf) || (d["confidence"] = conf)
        d
    end

    payload = Dict{String,Any}(
        "date"          => string(raw.date),
        "generated_at"  => string(raw.generated_at),
        "confidence_at" => string(now(UTC)),
        "total"         => Int(raw.total),
        "sources"       => collect(raw.sources),
        "companies"     => updated_companies,
    )

    out_path = DATA_FILE
    open(out_path, "w") do io
        JSON3.pretty(io, payload)
    end
    cp(out_path, replace(out_path, "latest" => "$(Dates.format(today(), "yyyymmdd"))"); force=true)

    # ── Summary ───────────────────────────────────────────────────────────────

    succeeded = top_n - length(failed)
    println()
    println("Confidence checks complete:")
    println("  Succeeded: $succeeded / $top_n")
    isempty(failed) || println("  Failed:    $(join(failed, "\n             "))")
    println()

    scored = [(string(c.symbol), string(c.name),
               get(confidence_by_symbol, string(c.symbol), nothing))
              for c in top
              if !isnothing(get(confidence_by_symbol, string(c.symbol), nothing))]
    sort!(scored, by = t -> (isnothing(t[3]) ? -1.0 : Float64(t[3]["score"])), rev=true)

    println("Top 20 by confidence score (of top-$top_n by market cap):")
    println("  #   Score  Pass  Symbol          Company")
    println("  " * "─"^70)
    for (rank, (sym, name, conf)) in enumerate(first(scored, 20))
        score   = isnothing(conf) ? "N/A" : @sprintf("%5.1f", conf["score"])
        verdict = isnothing(conf) ? "?" : (conf["pass"] ? "✓" : "✗")
        @printf("  %-3d %s  %s   %-15s %s\n", rank, score, verdict, sym, name)
    end
end

main()
